DROP TABLE IF EXISTS `loanapplications`;
CREATE TABLE IF NOT EXISTS `loanapplications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `MemberId` varchar(100) DEFAULT NULL,
  `Designation` varchar(100) DEFAULT NULL,
  `Savings` varchar(100) DEFAULT NULL,
  `LoanAmount` varchar(100) DEFAULT NULL,
  `LoanDuration` varchar(100) DEFAULT NULL,
  `InterestRate` varchar(100) DEFAULT NULL,
  `BankAccountName` varchar(100) DEFAULT NULL,
  `AccountType` varchar(100) DEFAULT NULL,
  `AccountNo` varchar(100) DEFAULT NULL,
  `BankName` varchar(100) DEFAULT NULL,
  `BranchName` varchar(100) DEFAULT NULL,
  `IncomeSource` varchar(100) DEFAULT NULL,
  
  `EnglishName` varchar(100) DEFAULT NULL,
  `DomainName` varchar(100) DEFAULT NULL,
  `DivisionOfficeId` varchar(100) DEFAULT NULL,
  `ZoneId` varchar(100) DEFAULT NULL,
  `AreaId` varchar(100) DEFAULT NULL,
  `BranchId` varchar(100) DEFAULT NULL,
  `TMSSId` varchar(100) DEFAULT NULL,
  

  `GaurantorName` varchar(100) DEFAULT NULL,
  `GFatherName` varchar(100) DEFAULT NULL,
  `GMotherName` varchar(100) DEFAULT NULL,
  `GHusbandWifeName` varchar(100) DEFAULT NULL,
  `GBirthDate` varchar(100) DEFAULT NULL,
  `GAge` varchar(100) DEFAULT NULL,
  `GNationality` varchar(100) DEFAULT NULL,
  `GOccupation` varchar(100) DEFAULT NULL,
  `GNId` varchar(100) DEFAULT NULL,
  `GTaxNo` varchar(100) DEFAULT NULL,
  `GDrivingLicenseNo` varchar(100) DEFAULT NULL,
  `GMobileNo` varchar(100) DEFAULT NULL,
  `GVillageName` varchar(100) DEFAULT NULL,
  `GPostOffice` varchar(100) DEFAULT NULL,
  `GPolliceStation` varchar(100) DEFAULT NULL,
  `GDistrict` varchar(100) DEFAULT NULL,

  `GOfficeName` varchar(100) DEFAULT NULL,
  `GDesignation` varchar(100) DEFAULT NULL,
  `GOfficeId` varchar(100) DEFAULT NULL,
  `GOfficeAddress` text DEFAULT NULL,
  `GBankAccountName` varchar(100) DEFAULT NULL,
  `GAccountType` varchar(100) DEFAULT NULL,
  `GAccountNo` varchar(100) DEFAULT NULL,
  `GBankName` varchar(100) DEFAULT NULL,
  `GTMemberId` varchar(100) DEFAULT NULL,
  `GBranchName` varchar(100) DEFAULT NULL,  
  `GAdmDate` varchar(100) DEFAULT NULL,
  `GSavingAmount` varchar(100) DEFAULT NULL,
  
  `GImage` varchar(100) DEFAULT NULL,
  `GSignature` varchar(100) DEFAULT NULL,
  `WName1` varchar(100) DEFAULT NULL,
  `WName2` varchar(100) DEFAULT NULL,
  `W1Signature` varchar(100) DEFAULT NULL,
  `W2Signature` varchar(100) DEFAULT NULL,
  `Approval1` int(2) DEFAULT NULL,  
  PRIMARY KEY (`id`),
  FULLTEXT KEY `idx_name` (`MemberId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;