-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.16-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for timf
-- DROP DATABASE IF EXISTS `timf`;
-- CREATE DATABASE IF NOT EXISTS `timf` /*!40100 DEFAULT CHARACTER SET latin1 */;
-- USE `timf`;


-- Dumping structure for table timf.thanas
DROP TABLE IF EXISTS `thanas`;
CREATE TABLE IF NOT EXISTS `thanas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ThanaNameBangla` varchar(500) DEFAULT NULL,
  `ThanaName` varchar(500) DEFAULT NULL,
  `DistrictId` int(11) DEFAULT NULL,
  `name` varchar(500) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=494 DEFAULT CHARSET=utf8;

-- Dumping data for table timf.thanas: ~493 rows (approximately)
DELETE FROM `thanas`;
/*!40000 ALTER TABLE `thanas` DISABLE KEYS */;
INSERT INTO `thanas` (`id`, `ThanaNameBangla`, `ThanaName`, `DistrictId`, `name`, `created_at`, `updated_at`) VALUES
	(1, 'আমতলী', 'Amtali Upazila', 34, NULL, NULL, NULL),
	(2, 'বামনা', 'Bamna Upazila', 34, NULL, NULL, NULL),
	(3, 'বরগুনা সদর', 'Barguna Sadar Upazila', 34, NULL, NULL, NULL),
	(4, 'বেতাগি', 'Betagi Upazila', 34, NULL, NULL, NULL),
	(5, 'পাথরঘাটা', 'Patharghata Upazila', 34, NULL, NULL, NULL),
	(6, 'তালতলী', 'Taltali Upazila', 34, NULL, NULL, NULL),
	(7, 'মুলাদি', 'Muladi Upazila', 35, NULL, NULL, NULL),
	(8, 'বাবুগঞ্জ', 'Babuganj Upazila', 35, NULL, NULL, NULL),
	(9, 'আগাইলঝরা', 'Agailjhara Upazila', 35, NULL, NULL, NULL),
	(10, 'বরিশাল সদর', 'Barisal Sadar Upazila', 35, NULL, NULL, NULL),
	(11, 'বাকেরগঞ্জ', 'Bakerganj Upazila', 35, NULL, NULL, NULL),
	(12, 'বানাড়িপারা', 'Banaripara Upazila', 35, NULL, NULL, NULL),
	(13, 'গৌরনদী', 'Gaurnadi Upazila', 35, NULL, NULL, NULL),
	(14, 'হিজলা', 'Hizla Upazila', 35, NULL, NULL, NULL),
	(15, 'মেহেদিগঞ্জ ', 'Mehendiganj Upazila', 35, NULL, NULL, NULL),
	(16, 'ওয়াজিরপুর', 'Wazirpur Upazila', 35, NULL, NULL, NULL),
	(17, 'ভোলা সদর', 'Bhola Sadar Upazila', 36, NULL, NULL, NULL),
	(18, 'বুরহানউদ্দিন', 'Burhanuddin Upazila', 36, NULL, NULL, NULL),
	(19, 'চর ফ্যাশন', 'Char Fasson Upazila', 36, NULL, NULL, NULL),
	(20, 'দৌলতখান', 'Daulatkhan Upazila', 36, NULL, NULL, NULL),
	(21, 'লালমোহন', 'Lalmohan Upazila', 36, NULL, NULL, NULL),
	(22, 'মনপুরা', 'Manpura Upazila', 36, NULL, NULL, NULL),
	(23, 'তাজুমুদ্দিন', 'Tazumuddin Upazila', 36, NULL, NULL, NULL),
	(24, 'ঝালকাঠি সদর', 'Jhalokati Sadar Upazila', 37, NULL, NULL, NULL),
	(25, 'কাঁঠালিয়া', 'Kathalia Upazila', 37, NULL, NULL, NULL),
	(26, 'নালচিতি', 'Nalchity Upazila', 37, NULL, NULL, NULL),
	(27, 'রাজাপুর', 'Rajapur Upazila', 37, NULL, NULL, NULL),
	(28, 'বাউফল', 'Bauphal Upazila', 38, NULL, NULL, NULL),
	(29, 'দশমিনা', 'Dashmina Upazila', 38, NULL, NULL, NULL),
	(30, 'গলাচিপা', 'Galachipa Upazila', 38, NULL, NULL, NULL),
	(31, 'কালাপারা', 'Kalapara Upazila', 38, NULL, NULL, NULL),
	(32, 'মির্জাগঞ্জ ', 'Mirzaganj Upazila', 38, NULL, NULL, NULL),
	(33, 'পটুয়াখালী সদর', 'Patuakhali Sadar Upazila', 38, NULL, NULL, NULL),
	(34, 'ডুমকি', 'Dumki Upazila', 38, NULL, NULL, NULL),
	(35, 'রাঙ্গাবালি', 'Rangabali Upazila', 38, NULL, NULL, NULL),
	(36, 'ভ্যান্ডারিয়া', 'Bhandaria', 39, NULL, NULL, NULL),
	(37, 'কাউখালি', 'Kaukhali', 39, NULL, NULL, NULL),
	(38, 'মাঠবাড়িয়া', 'Mathbaria', 39, NULL, NULL, NULL),
	(39, 'নাজিরপুর', 'Nazirpur', 39, NULL, NULL, NULL),
	(40, 'নেসারাবাদ', 'Nesarabad', 39, NULL, NULL, NULL),
	(41, 'পিরোজপুর সদর', 'Pirojpur Sadar', 39, NULL, NULL, NULL),
	(42, 'জিয়ানগর', 'Zianagar', 39, NULL, NULL, NULL),
	(43, 'বান্দরবন সদর', 'Bandarban Sadar', 40, NULL, NULL, NULL),
	(44, 'থানচি', 'Thanchi', 40, NULL, NULL, NULL),
	(45, 'লামা', 'Lama', 40, NULL, NULL, NULL),
	(46, 'নাইখংছড়ি ', 'Naikhongchhari', 40, NULL, NULL, NULL),
	(47, 'আলী কদম', 'Ali kadam', 40, NULL, NULL, NULL),
	(48, 'রউয়াংছড়ি ', 'Rowangchhari', 40, NULL, NULL, NULL),
	(49, 'রুমা', 'Ruma', 40, NULL, NULL, NULL),
	(50, 'ব্রাহ্মণবাড়িয়া সদর', 'Brahmanbaria Sadar Upazila', 41, NULL, NULL, NULL),
	(51, 'আশুগঞ্জ', 'Ashuganj Upazila', 41, NULL, NULL, NULL),
	(52, 'নাসির নগর', 'Nasirnagar Upazila', 41, NULL, NULL, NULL),
	(53, 'নবীনগর', 'Nabinagar Upazila', 41, NULL, NULL, NULL),
	(54, 'সরাইল', 'Sarail Upazila', 41, NULL, NULL, NULL),
	(55, 'শাহবাজপুর টাউন', 'Shahbazpur Town', 41, NULL, NULL, NULL),
	(56, 'কসবা', 'Kasba Upazila', 41, NULL, NULL, NULL),
	(57, 'আখাউরা', 'Akhaura Upazila', 41, NULL, NULL, NULL),
	(58, 'বাঞ্ছারামপুর', 'Bancharampur Upazila', 41, NULL, NULL, NULL),
	(59, 'বিজয় নগর', 'Bijoynagar Upazila', 41, NULL, NULL, NULL),
	(60, 'চাঁদপুর সদর', 'Chandpur Sadar', 42, NULL, NULL, NULL),
	(61, 'ফরিদগঞ্জ', 'Faridganj', 42, NULL, NULL, NULL),
	(62, 'হাইমচর', 'Haimchar', 42, NULL, NULL, NULL),
	(63, 'হাজীগঞ্জ', 'Haziganj', 42, NULL, NULL, NULL),
	(64, 'কচুয়া', 'Kachua', 42, NULL, NULL, NULL),
	(65, 'মতলব উত্তর', 'Matlab Uttar', 42, NULL, NULL, NULL),
	(66, 'মতলব দক্ষিণ', 'Matlab Dakkhin', 42, NULL, NULL, NULL),
	(67, 'শাহরাস্তি', 'Shahrasti', 42, NULL, NULL, NULL),
	(68, 'আনোয়ারা', 'Anwara Upazila', 43, NULL, NULL, NULL),
	(69, 'বাশখালি', 'Banshkhali Upazila', 43, NULL, NULL, NULL),
	(70, 'বোয়ালখালি', 'Boalkhali Upazila', 43, NULL, NULL, NULL),
	(71, 'চন্দনাইশ', 'Chandanaish Upazila', 43, NULL, NULL, NULL),
	(72, 'ফটিকছড়ি', 'Fatikchhari Upazila', 43, NULL, NULL, NULL),
	(73, 'হাঠহাজারী', 'Hathazari Upazila', 43, NULL, NULL, NULL),
	(74, 'লোহাগারা', 'Lohagara Upazila', 43, NULL, NULL, NULL),
	(75, 'মিরসরাই', 'Mirsharai Upazila', 43, NULL, NULL, NULL),
	(76, 'পটিয়া', 'Patiya Upazila', 43, NULL, NULL, NULL),
	(77, 'রাঙ্গুনিয়া', 'Rangunia Upazila', 43, NULL, NULL, NULL),
	(78, 'রাউজান', 'Raozan Upazila', 43, NULL, NULL, NULL),
	(79, 'সন্দ্বীপ', 'Sandwip Upazila', 43, NULL, NULL, NULL),
	(80, 'সাতকানিয়া', 'Satkania Upazila', 43, NULL, NULL, NULL),
	(81, 'সীতাকুণ্ড', 'Sitakunda Upazila', 43, NULL, NULL, NULL),
	(82, 'বড়ুরা', 'Barura Upazila', 44, NULL, NULL, NULL),
	(83, 'ব্রাহ্মণপাড়া', 'Brahmanpara Upazila', 44, NULL, NULL, NULL),
	(84, 'বুড়িচং', 'Burichong Upazila', 44, NULL, NULL, NULL),
	(85, 'চান্দিনা', 'Chandina Upazila', 44, NULL, NULL, NULL),
	(86, 'চৌদ্দগ্রাম', 'Chauddagram Upazila', 44, NULL, NULL, NULL),
	(87, 'দাউদকান্দি', 'Daudkandi Upazila', 44, NULL, NULL, NULL),
	(88, 'দেবীদ্বার', 'Debidwar Upazila', 44, NULL, NULL, NULL),
	(89, 'হোমনা', 'Homna Upazila', 44, NULL, NULL, NULL),
	(90, 'কুমিল্লা সদর', 'Comilla Sadar Upazila', 44, NULL, NULL, NULL),
	(91, 'লাকসাম', 'Laksam Upazila', 44, NULL, NULL, NULL),
	(92, 'মনোহরগঞ্জ', 'Monohorgonj Upazila', 44, NULL, NULL, NULL),
	(93, 'মেঘনা', 'Meghna Upazila', 44, NULL, NULL, NULL),
	(94, 'মুরাদনগর', 'Muradnagar Upazila', 44, NULL, NULL, NULL),
	(95, 'নাঙ্গালকোট', 'Nangalkot Upazila', 44, NULL, NULL, NULL),
	(96, 'কুমিল্লা সদর দক্ষিণ', 'Comilla Sadar South Upazila', 44, NULL, NULL, NULL),
	(97, 'তিতাস', 'Titas Upazila', 44, NULL, NULL, NULL),
	(98, 'চকরিয়া', 'Chakaria Upazila', 45, NULL, NULL, NULL),
	(99, 'চকরিয়া', 'Chakaria Upazila', 45, NULL, NULL, NULL),
	(100, 'কক্স বাজার সদর', 'Cox\'s Bazar Sadar Upazila', 45, NULL, NULL, NULL),
	(101, 'কুতুবদিয়া', 'Kutubdia Upazila', 45, NULL, NULL, NULL),
	(102, 'মহেশখালী', 'Maheshkhali Upazila', 45, NULL, NULL, NULL),
	(103, 'রামু', 'Ramu Upazila', 45, NULL, NULL, NULL),
	(104, 'টেকনাফ', 'Teknaf Upazila', 45, NULL, NULL, NULL),
	(105, 'উখিয়া', 'Ukhia Upazila', 45, NULL, NULL, NULL),
	(106, 'পেকুয়া', 'Pekua Upazila', 45, NULL, NULL, NULL),
	(107, 'ফেনী সদর', 'Feni Sadar', 46, NULL, NULL, NULL),
	(108, 'ছাগল নাইয়া', 'Chagalnaiya', 46, NULL, NULL, NULL),
	(109, 'দাগানভিয়া', 'Daganbhyan', 46, NULL, NULL, NULL),
	(110, 'পরশুরাম', 'Parshuram', 46, NULL, NULL, NULL),
	(111, 'ফুলগাজি', 'Fhulgazi', 46, NULL, NULL, NULL),
	(112, 'সোনাগাজি', 'Sonagazi', 46, NULL, NULL, NULL),
	(113, 'দিঘিনালা ', 'Dighinala Upazila', 47, NULL, NULL, NULL),
	(114, 'খাগড়াছড়ি', 'Khagrachhari Upazila', 47, NULL, NULL, NULL),
	(115, 'লক্ষ্মীছড়ি', 'Lakshmichhari Upazila', 47, NULL, NULL, NULL),
	(116, 'মহলছড়ি', 'Mahalchhari Upazila', 47, NULL, NULL, NULL),
	(117, 'মানিকছড়ি', 'Manikchhari Upazila', 47, NULL, NULL, NULL),
	(118, 'মাটিরাঙ্গা', 'Matiranga Upazila', 47, NULL, NULL, NULL),
	(119, 'পানছড়ি', 'Panchhari Upazila', 47, NULL, NULL, NULL),
	(120, 'রামগড়', 'Ramgarh Upazila', 47, NULL, NULL, NULL),
	(121, 'লক্ষ্মীপুর সদর', 'Lakshmipur Sadar Upazila', 48, NULL, NULL, NULL),
	(122, 'রায়পুর', 'Raipur Upazila', 48, NULL, NULL, NULL),
	(123, 'রামগঞ্জ', 'Ramganj Upazila', 48, NULL, NULL, NULL),
	(124, 'রামগতি', 'Ramgati Upazila', 48, NULL, NULL, NULL),
	(125, 'কমল নগর', 'Komol Nagar Upazila', 48, NULL, NULL, NULL),
	(126, 'নোয়াখালী সদর', 'Noakhali Sadar Upazila', 49, NULL, NULL, NULL),
	(127, 'বেগমগঞ্জ', 'Begumganj Upazila', 49, NULL, NULL, NULL),
	(128, 'চাটখিল', 'Chatkhil Upazila', 49, NULL, NULL, NULL),
	(129, 'কোম্পানীগঞ্জ', 'Companyganj Upazila', 49, NULL, NULL, NULL),
	(130, 'শেনবাগ', 'Shenbag Upazila', 49, NULL, NULL, NULL),
	(131, 'হাতিয়া', 'Hatia Upazila', 49, NULL, NULL, NULL),
	(132, 'কবিরহাট ', 'Kobirhat Upazila', 49, NULL, NULL, NULL),
	(133, 'সোনাইমুরি', 'Sonaimuri Upazila', 49, NULL, NULL, NULL),
	(134, 'সুবর্ণ চর ', 'Suborno Char Upazila', 49, NULL, NULL, NULL),
	(135, 'রাঙ্গামাটি সদর', 'Rangamati Sadar Upazila', 50, NULL, NULL, NULL),
	(136, 'বেলাইছড়ি', 'Belaichhari Upazila', 50, NULL, NULL, NULL),
	(137, 'বাঘাইছড়ি', 'Bagaichhari Upazila', 50, NULL, NULL, NULL),
	(138, 'বরকল', 'Barkal Upazila', 50, NULL, NULL, NULL),
	(139, 'জুরাইছড়ি', 'Juraichhari Upazila', 50, NULL, NULL, NULL),
	(140, 'রাজাস্থলি', 'Rajasthali Upazila', 50, NULL, NULL, NULL),
	(141, 'কাপ্তাই', 'Kaptai Upazila', 50, NULL, NULL, NULL),
	(142, 'লাঙ্গাডু', 'Langadu Upazila', 50, NULL, NULL, NULL),
	(143, 'নান্নেরচর ', 'Nannerchar Upazila', 50, NULL, NULL, NULL),
	(144, 'কাউখালি', 'Kaukhali Upazila', 50, NULL, NULL, NULL),
	(145, 'ধামরাই', 'Dhamrai Upazila', 1, NULL, NULL, NULL),
	(146, 'দোহার', 'Dohar Upazila', 1, NULL, NULL, NULL),
	(147, 'কেরানীগঞ্জ', 'Keraniganj Upazila', 1, NULL, NULL, NULL),
	(148, 'নবাবগঞ্জ', 'Nawabganj Upazila', 1, NULL, NULL, NULL),
	(149, 'সাভার', 'Savar Upazila', 1, NULL, NULL, NULL),
	(150, 'ফরিদপুর সদর', 'Faridpur Sadar Upazila', 2, NULL, NULL, NULL),
	(151, 'বোয়ালমারী', 'Boalmari Upazila', 2, NULL, NULL, NULL),
	(152, 'আলফাডাঙ্গা', 'Alfadanga Upazila', 2, NULL, NULL, NULL),
	(153, 'মধুখালি', 'Madhukhali Upazila', 2, NULL, NULL, NULL),
	(154, 'ভাঙ্গা', 'Bhanga Upazila', 2, NULL, NULL, NULL),
	(155, 'নগরকান্ড', 'Nagarkanda Upazila', 2, NULL, NULL, NULL),
	(156, 'চরভদ্রাসন ', 'Charbhadrasan Upazila', 2, NULL, NULL, NULL),
	(157, 'সদরপুর', 'Sadarpur Upazila', 2, NULL, NULL, NULL),
	(158, 'শালথা', 'Shaltha Upazila', 2, NULL, NULL, NULL),
	(159, 'গাজীপুর সদর', 'Gazipur Sadar-Joydebpur', 3, NULL, NULL, NULL),
	(160, 'কালিয়াকৈর', 'Kaliakior', 3, NULL, NULL, NULL),
	(161, 'কাপাসিয়া', 'Kapasia', 3, NULL, NULL, NULL),
	(162, 'শ্রীপুর', 'Sripur', 3, NULL, NULL, NULL),
	(163, 'কালীগঞ্জ', 'Kaliganj', 3, NULL, NULL, NULL),
	(164, 'টঙ্গি', 'Tongi', 3, NULL, NULL, NULL),
	(165, 'গোপালগঞ্জ সদর', 'Gopalganj Sadar Upazila', 4, NULL, NULL, NULL),
	(166, 'কাশিয়ানি', 'Kashiani Upazila', 4, NULL, NULL, NULL),
	(167, 'কোটালিপাড়া', 'Kotalipara Upazila', 4, NULL, NULL, NULL),
	(168, 'মুকসুদপুর', 'Muksudpur Upazila', 4, NULL, NULL, NULL),
	(169, 'টুঙ্গিপাড়া', 'Tungipara Upazila', 4, NULL, NULL, NULL),
	(170, 'দেওয়ানগঞ্জ', 'Dewanganj Upazila', 5, NULL, NULL, NULL),
	(171, 'বকসিগঞ্জ', 'Baksiganj Upazila', 5, NULL, NULL, NULL),
	(172, 'ইসলামপুর', 'Islampur Upazila', 5, NULL, NULL, NULL),
	(173, 'জামালপুর সদর', 'Jamalpur Sadar Upazila', 5, NULL, NULL, NULL),
	(174, 'মাদারগঞ্জ', 'Madarganj Upazila', 5, NULL, NULL, NULL),
	(175, 'মেলানদাহা', 'Melandaha Upazila', 5, NULL, NULL, NULL),
	(176, 'সরিষাবাড়ি ', 'Sarishabari Upazila', 5, NULL, NULL, NULL),
	(177, 'নারুন্দি', 'Narundi Police I.C', 5, NULL, NULL, NULL),
	(178, 'অষ্টগ্রাম', 'Astagram Upazila', 6, NULL, NULL, NULL),
	(179, 'বাজিতপুর', 'Bajitpur Upazila', 6, NULL, NULL, NULL),
	(180, 'ভৈরব', 'Bhairab Upazila', 6, NULL, NULL, NULL),
	(181, 'হোসেনপুর ', 'Hossainpur Upazila', 6, NULL, NULL, NULL),
	(182, 'ইটনা', 'Itna Upazila', 6, NULL, NULL, NULL),
	(183, 'করিমগঞ্জ', 'Karimganj Upazila', 6, NULL, NULL, NULL),
	(184, 'কতিয়াদি', 'Katiadi Upazila', 6, NULL, NULL, NULL),
	(185, 'কিশোরগঞ্জ সদর', 'Kishoreganj Sadar Upazila', 6, NULL, NULL, NULL),
	(186, 'কুলিয়ারচর', 'Kuliarchar Upazila', 6, NULL, NULL, NULL),
	(187, 'মিঠামাইন', 'Mithamain Upazila', 6, NULL, NULL, NULL),
	(188, 'নিকলি', 'Nikli Upazila', 6, NULL, NULL, NULL),
	(189, 'পাকুন্ডা', 'Pakundia Upazila', 6, NULL, NULL, NULL),
	(190, 'তাড়াইল', 'Tarail Upazila', 6, NULL, NULL, NULL),
	(191, 'মাদারীপুর সদর', 'Madaripur Sadar', 7, NULL, NULL, NULL),
	(192, 'কালকিনি', 'Kalkini', 7, NULL, NULL, NULL),
	(193, 'রাজইর', 'Rajoir', 7, NULL, NULL, NULL),
	(194, 'শিবচর', 'Shibchar', 7, NULL, NULL, NULL),
	(195, 'মানিকগঞ্জ সদর', 'Manikganj Sadar Upazila', 8, NULL, NULL, NULL),
	(196, 'সিঙ্গাইর', 'Singair Upazila', 8, NULL, NULL, NULL),
	(197, 'শিবালয়', 'Shibalaya Upazila', 8, NULL, NULL, NULL),
	(198, 'সাঠুরিয়া', 'Saturia Upazila', 8, NULL, NULL, NULL),
	(199, 'হরিরামপুর', 'Harirampur Upazila', 8, NULL, NULL, NULL),
	(200, 'ঘিওর', 'Ghior Upazila', 8, NULL, NULL, NULL),
	(201, 'দৌলতপুর', 'Daulatpur Upazila', 8, NULL, NULL, NULL),
	(202, 'লোহাজং', 'Lohajang Upazila', 9, NULL, NULL, NULL),
	(203, 'শ্রীনগর', 'Sreenagar Upazila', 9, NULL, NULL, NULL),
	(204, 'মুন্সিগঞ্জ সদর', 'Munshiganj Sadar Upazila', 9, NULL, NULL, NULL),
	(205, 'সিরাজদিখান', 'Sirajdikhan Upazila', 9, NULL, NULL, NULL),
	(206, 'টঙ্গিবাড়ি', 'Tongibari Upazila', 9, NULL, NULL, NULL),
	(207, 'গজারিয়া', 'Gazaria Upazila', 9, NULL, NULL, NULL),
	(208, 'ভালুকা', 'Bhaluka', 10, NULL, NULL, NULL),
	(209, 'ত্রিশাল', 'Trishal', 10, NULL, NULL, NULL),
	(210, 'হালুয়াঘাট', 'Haluaghat', 10, NULL, NULL, NULL),
	(211, 'মুক্তাগাছা', 'Muktagachha', 10, NULL, NULL, NULL),
	(212, 'ধবারুয়া', 'Dhobaura', 10, NULL, NULL, NULL),
	(213, 'ফুলবাড়িয়া', 'Fulbaria', 10, NULL, NULL, NULL),
	(214, 'গফরগাঁও', 'Gaffargaon', 10, NULL, NULL, NULL),
	(215, 'গৌরিপুর', 'Gauripur', 10, NULL, NULL, NULL),
	(216, 'ঈশ্বরগঞ্জ', 'Ishwarganj', 10, NULL, NULL, NULL),
	(217, 'ময়মনসিং সদর', 'Mymensingh Sadar', 10, NULL, NULL, NULL),
	(218, 'নন্দাইল', 'Nandail', 10, NULL, NULL, NULL),
	(219, 'ফুলপুর', 'Phulpur', 10, NULL, NULL, NULL),
	(220, 'আড়াইহাজার', 'Araihazar Upazila', 11, NULL, NULL, NULL),
	(221, 'সোনারগাঁও', 'Sonargaon Upazila', 11, NULL, NULL, NULL),
	(222, 'বান্দার', 'Bandar', 11, NULL, NULL, NULL),
	(223, 'নারায়ানগঞ্জ সদর', 'Naryanganj Sadar Upazila', 11, NULL, NULL, NULL),
	(224, 'রূপগঞ্জ', 'Rupganj Upazila', 11, NULL, NULL, NULL),
	(225, 'সিদ্ধিরগঞ্জ', 'Siddirgonj Upazila', 11, NULL, NULL, NULL),
	(226, 'বেলাবো', 'Belabo Upazila', 12, NULL, NULL, NULL),
	(227, 'মনোহরদি', 'Monohardi Upazila', 12, NULL, NULL, NULL),
	(228, 'নরসিংদী সদর', 'Narsingdi Sadar Upazila', 12, NULL, NULL, NULL),
	(229, 'পলাশ', 'Palash Upazila', 12, NULL, NULL, NULL),
	(230, 'রায়পুর', 'Raipura Upazila, Narsingdi', 12, NULL, NULL, NULL),
	(231, 'শিবপুর', 'Shibpur Upazila', 12, NULL, NULL, NULL),
	(232, 'কেন্দুয়া', 'Kendua Upazilla', 13, NULL, NULL, NULL),
	(233, 'আটপাড়া', 'Atpara Upazilla', 13, NULL, NULL, NULL),
	(234, 'বরহাট্টা', 'Barhatta Upazilla', 13, NULL, NULL, NULL),
	(235, 'দুর্গাপুর', 'Durgapur Upazilla', 13, NULL, NULL, NULL),
	(236, 'কলমাকান্দা', 'Kalmakanda Upazilla', 13, NULL, NULL, NULL),
	(237, 'মদন', 'Madan Upazilla', 13, NULL, NULL, NULL),
	(238, 'মোহনগঞ্জ', 'Mohanganj Upazilla', 13, NULL, NULL, NULL),
	(239, 'নেত্রকোনা সদর', 'Netrakona-S Upazilla', 13, NULL, NULL, NULL),
	(240, 'পূর্বধলা', 'Purbadhala Upazilla', 13, NULL, NULL, NULL),
	(241, 'খালিয়াজুরি', 'Khaliajuri Upazilla', 13, NULL, NULL, NULL),
	(242, 'বালিয়াকান্দি', 'Baliakandi Upazila', 14, NULL, NULL, NULL),
	(243, 'গোয়ালন্দ ঘাট', 'Goalandaghat Upazila', 14, NULL, NULL, NULL),
	(244, 'পাংশা', 'Pangsha Upazila', 14, NULL, NULL, NULL),
	(245, 'কালুখালি', 'Kalukhali Upazila', 14, NULL, NULL, NULL),
	(246, 'রাজবাড়ি সদর', 'Rajbari Sadar Upazila', 14, NULL, NULL, NULL),
	(247, 'শরীয়তপুর সদর ', 'Shariatpur Sadar -Palong', 15, NULL, NULL, NULL),
	(248, 'দামুদিয়া', 'Damudya Upazila', 15, NULL, NULL, NULL),
	(249, 'নড়িয়া', 'Naria Upazila', 15, NULL, NULL, NULL),
	(250, 'জাজিরা', 'Jajira Upazila', 15, NULL, NULL, NULL),
	(251, 'ভেদারগঞ্জ', 'Bhedarganj Upazila', 15, NULL, NULL, NULL),
	(252, 'গোসাইর হাট ', 'Gosairhat Upazila', 15, NULL, NULL, NULL),
	(253, 'ঝিনাইগাতি', 'Jhenaigati Upazila', 16, NULL, NULL, NULL),
	(254, 'নাকলা', 'Nakla Upazila', 16, NULL, NULL, NULL),
	(255, 'নালিতাবাড়ি', 'Nalitabari Upazila', 16, NULL, NULL, NULL),
	(256, 'শেরপুর সদর', 'Sherpur Sadar Upazila', 16, NULL, NULL, NULL),
	(257, 'শ্রীবরদি', 'Sreebardi Upazila', 16, NULL, NULL, NULL),
	(258, 'টাঙ্গাইল সদর', 'Tangail Sadar Upazila', 17, NULL, NULL, NULL),
	(259, 'সখিপুর', 'Sakhipur Upazila', 17, NULL, NULL, NULL),
	(260, 'বসাইল', 'Basail Upazila', 17, NULL, NULL, NULL),
	(261, 'মধুপুর', 'Madhupur Upazila', 17, NULL, NULL, NULL),
	(262, 'ঘাটাইল', 'Ghatail Upazila', 17, NULL, NULL, NULL),
	(263, 'কালিহাতি', 'Kalihati Upazila', 17, NULL, NULL, NULL),
	(264, 'নগরপুর', 'Nagarpur Upazila', 17, NULL, NULL, NULL),
	(265, 'মির্জাপুর', 'Mirzapur Upazila', 17, NULL, NULL, NULL),
	(266, 'গোপালপুর', 'Gopalpur Upazila', 17, NULL, NULL, NULL),
	(267, 'দেলদুয়ার', 'Delduar Upazila', 17, NULL, NULL, NULL),
	(268, 'ভুয়াপুর', 'Bhuapur Upazila', 17, NULL, NULL, NULL),
	(269, 'ধানবাড়ি', 'Dhanbari Upazila', 17, NULL, NULL, NULL),
	(270, 'বাগেরহাট সদর', 'Bagerhat Sadar Upazila', 55, NULL, NULL, NULL),
	(271, 'চিতলমাড়ি', 'Chitalmari Upazila', 55, NULL, NULL, NULL),
	(272, 'ফকিরহাট', 'Fakirhat Upazila', 55, NULL, NULL, NULL),
	(273, 'কচুয়া', 'Kachua Upazila', 55, NULL, NULL, NULL),
	(274, 'মোল্লাহাট ', 'Mollahat Upazila', 55, NULL, NULL, NULL),
	(275, 'মংলা', 'Mongla Upazila', 55, NULL, NULL, NULL),
	(276, 'মরেলগঞ্জ', 'Morrelganj Upazila', 55, NULL, NULL, NULL),
	(277, 'রামপাল', 'Rampal Upazila', 55, NULL, NULL, NULL),
	(278, 'স্মরণখোলা', 'Sarankhola Upazila', 55, NULL, NULL, NULL),
	(279, 'দামুরহুদা', 'Damurhuda Upazila', 56, NULL, NULL, NULL),
	(280, 'চুয়াডাঙ্গা সদর', 'Chuadanga-S Upazila', 56, NULL, NULL, NULL),
	(281, 'জীবন নগর ', 'Jibannagar Upazila', 56, NULL, NULL, NULL),
	(282, 'আলমডাঙ্গা', 'Alamdanga Upazila', 56, NULL, NULL, NULL),
	(283, 'অভয়নগর', 'Abhaynagar Upazila', 57, NULL, NULL, NULL),
	(284, 'কেশবপুর', 'Keshabpur Upazila', 57, NULL, NULL, NULL),
	(285, 'বাঘের পাড়া ', 'Bagherpara Upazila', 57, NULL, NULL, NULL),
	(286, 'যশোর সদর', 'Jessore Sadar Upazila', 57, NULL, NULL, NULL),
	(287, 'চৌগাছা', 'Chaugachha Upazila', 57, NULL, NULL, NULL),
	(288, 'মনিরামপুর ', 'Manirampur Upazila', 57, NULL, NULL, NULL),
	(289, 'ঝিকরগাছা', 'Jhikargachha Upazila', 57, NULL, NULL, NULL),
	(290, 'সারশা', 'Sharsha Upazila', 57, NULL, NULL, NULL),
	(291, 'ঝিনাইদহ সদর', 'Jhenaidah Sadar Upazila', 58, NULL, NULL, NULL),
	(292, 'মহেশপুর', 'Maheshpur Upazila', 58, NULL, NULL, NULL),
	(293, 'কালীগঞ্জ', 'Kaliganj Upazila', 58, NULL, NULL, NULL),
	(294, 'কোট চাঁদপুর ', 'Kotchandpur Upazila', 58, NULL, NULL, NULL),
	(295, 'শৈলকুপা', 'Shailkupa Upazila', 58, NULL, NULL, NULL),
	(296, 'হাড়িনাকুন্দা', 'Harinakunda Upazila', 58, NULL, NULL, NULL),
	(297, 'তেরোখাদা', 'Terokhada Upazila', 59, NULL, NULL, NULL),
	(298, 'বাটিয়াঘাটা ', 'Batiaghata Upazila', 59, NULL, NULL, NULL),
	(299, 'ডাকপে', 'Dacope Upazila', 59, NULL, NULL, NULL),
	(300, 'ডুমুরিয়া', 'Dumuria Upazila', 59, NULL, NULL, NULL),
	(301, 'দিঘলিয়া', 'Dighalia Upazila', 59, NULL, NULL, NULL),
	(302, 'কয়ড়া', 'Koyra Upazila', 59, NULL, NULL, NULL),
	(303, 'পাইকগাছা', 'Paikgachha Upazila', 59, NULL, NULL, NULL),
	(304, 'ফুলতলা', 'Phultala Upazila', 59, NULL, NULL, NULL),
	(305, 'রূপসা', 'Rupsa Upazila', 59, NULL, NULL, NULL),
	(306, 'কুষ্টিয়া সদর', 'Kushtia Sadar', 60, NULL, NULL, NULL),
	(307, 'কুমারখালি', 'Kumarkhali', 60, NULL, NULL, NULL),
	(308, 'দৌলতপুর', 'Daulatpur', 60, NULL, NULL, NULL),
	(309, 'মিরপুর', 'Mirpur', 60, NULL, NULL, NULL),
	(310, 'ভেরামারা', 'Bheramara', 60, NULL, NULL, NULL),
	(311, 'খোকসা', 'Khoksa', 60, NULL, NULL, NULL),
	(312, 'মাগুরা সদর', 'Magura Sadar Upazila', 61, NULL, NULL, NULL),
	(313, 'মোহাম্মাদপুর', 'Mohammadpur Upazila', 61, NULL, NULL, NULL),
	(314, 'শালিখা', 'Shalikha Upazila', 61, NULL, NULL, NULL),
	(315, 'শ্রীপুর', 'Sreepur Upazila', 61, NULL, NULL, NULL),
	(316, 'আংনি', 'angni Upazila', 62, NULL, NULL, NULL),
	(317, 'মুজিব নগর', 'Mujib Nagar Upazila', 62, NULL, NULL, NULL),
	(318, 'মেহেরপুর সদর', 'Meherpur-S Upazila', 62, NULL, NULL, NULL),
	(319, 'নড়াইল সদর', 'Narail-S Upazilla', 63, NULL, NULL, NULL),
	(320, 'লোহাগাড়া', 'Lohagara Upazilla', 63, NULL, NULL, NULL),
	(321, 'কালিয়া', 'Kalia Upazilla', 63, NULL, NULL, NULL),
	(322, 'সাতক্ষীরা সদর', 'Satkhira Sadar Upazila', 64, NULL, NULL, NULL),
	(323, 'আসসাশুনি ', 'Assasuni Upazila', 64, NULL, NULL, NULL),
	(324, 'দেভাটা', 'Debhata Upazila', 64, NULL, NULL, NULL),
	(325, 'তালা', 'Tala Upazila', 64, NULL, NULL, NULL),
	(326, 'কলরোয়া', 'Kalaroa Upazila', 64, NULL, NULL, NULL),
	(327, 'কালীগঞ্জ', 'Kaliganj Upazila', 64, NULL, NULL, NULL),
	(328, 'শ্যামনগর', 'Shyamnagar Upazila', 64, NULL, NULL, NULL),
	(329, 'আদমদিঘী', 'Adamdighi', 18, NULL, NULL, NULL),
	(330, 'বগুড়া সদর', 'Bogra Sadar', 18, NULL, NULL, NULL),
	(331, 'শেরপুর', 'Sherpur', 18, NULL, NULL, NULL),
	(332, 'ধুনট', 'Dhunat', 18, NULL, NULL, NULL),
	(333, 'দুপচাচিয়া', 'Dhupchanchia', 18, NULL, NULL, NULL),
	(334, 'গাবতলি', 'Gabtali', 18, NULL, NULL, NULL),
	(335, 'কাহালু', 'Kahaloo', 18, NULL, NULL, NULL),
	(336, 'নন্দিগ্রাম', 'Nandigram', 18, NULL, NULL, NULL),
	(337, 'শাহজাহানপুর', 'Sahajanpur', 18, NULL, NULL, NULL),
	(338, 'সারিয়াকান্দি', 'Sariakandi', 18, NULL, NULL, NULL),
	(339, 'শিবগঞ্জ', 'Shibganj', 18, NULL, NULL, NULL),
	(340, 'সোনাতলা', 'Sonatala', 18, NULL, NULL, NULL),
	(341, 'জয়পুরহাট সদর', 'Joypurhat S', 19, NULL, NULL, NULL),
	(342, 'আক্কেলপুর', 'Akkelpur', 19, NULL, NULL, NULL),
	(343, 'কালাই', 'Kalai', 19, NULL, NULL, NULL),
	(344, 'খেতলাল', 'Khetlal', 19, NULL, NULL, NULL),
	(345, 'পাঁচবিবি', 'Panchbibi', 19, NULL, NULL, NULL),
	(346, 'নওগাঁ সদর', 'Naogaon Sadar Upazila', 20, NULL, NULL, NULL),
	(347, 'মহাদেবপুর', 'Mohadevpur Upazila', 20, NULL, NULL, NULL),
	(348, 'মান্দা', 'Manda Upazila', 20, NULL, NULL, NULL),
	(349, 'নিয়ামতপুর', 'Niamatpur Upazila', 20, NULL, NULL, NULL),
	(350, 'আত্রাই', 'Atrai Upazila', 20, NULL, NULL, NULL),
	(351, 'রাণীনগর', 'Raninagar Upazila', 20, NULL, NULL, NULL),
	(352, 'পত্নীতলা', 'Patnitala Upazila', 20, NULL, NULL, NULL),
	(353, 'ধামইরহাট ', 'Dhamoirhat Upazila', 20, NULL, NULL, NULL),
	(354, 'সাপাহার', 'Sapahar Upazila', 20, NULL, NULL, NULL),
	(355, 'পোরশা', 'Porsha Upazila', 20, NULL, NULL, NULL),
	(356, 'বদলগাছি', 'Badalgachhi Upazila', 20, NULL, NULL, NULL),
	(357, 'নাটোর সদর', 'Natore Sadar Upazila', 21, NULL, NULL, NULL),
	(358, 'বড়াইগ্রাম', 'Baraigram Upazila', 21, NULL, NULL, NULL),
	(359, 'বাগাতিপাড়া', 'Bagatipara Upazila', 21, NULL, NULL, NULL),
	(360, 'লালপুর', 'Lalpur Upazila', 21, NULL, NULL, NULL),
	(361, 'নাটোর সদর', 'Natore Sadar Upazila', 21, NULL, NULL, NULL),
	(362, 'বড়াই গ্রাম', 'Baraigram Upazila', 21, NULL, NULL, NULL),
	(363, 'ভোলাহাট', 'Bholahat Upazila', 22, NULL, NULL, NULL),
	(364, 'গোমস্তাপুর', 'Gomastapur Upazila', 22, NULL, NULL, NULL),
	(365, 'নাচোল', 'Nachole Upazila', 22, NULL, NULL, NULL),
	(366, 'নবাবগঞ্জ সদর', 'Nawabganj Sadar Upazila', 22, NULL, NULL, NULL),
	(367, 'শিবগঞ্জ', 'Shibganj Upazila', 22, NULL, NULL, NULL),
	(368, 'আটঘরিয়া', 'Atgharia Upazila', 23, NULL, NULL, NULL),
	(369, 'বেড়া', 'Bera Upazila', 23, NULL, NULL, NULL),
	(370, 'ভাঙ্গুরা', 'Bhangura Upazila', 23, NULL, NULL, NULL),
	(371, 'চাটমোহর', 'Chatmohar Upazila', 23, NULL, NULL, NULL),
	(372, 'ফরিদপুর', 'Faridpur Upazila', 23, NULL, NULL, NULL),
	(373, 'ঈশ্বরদী', 'Ishwardi Upazila', 23, NULL, NULL, NULL),
	(374, 'পাবনা সদর', 'Pabna Sadar Upazila', 23, NULL, NULL, NULL),
	(375, 'সাথিয়া', 'Santhia Upazila', 23, NULL, NULL, NULL),
	(376, 'সুজানগর', 'Sujanagar Upazila', 23, NULL, NULL, NULL),
	(377, 'বাঘা', 'Bagha', 24, NULL, NULL, NULL),
	(378, 'বাগমারা', 'Bagmara', 24, NULL, NULL, NULL),
	(379, 'চারঘাট', 'Charghat', 24, NULL, NULL, NULL),
	(380, 'দুর্গাপুর', 'Durgapur', 24, NULL, NULL, NULL),
	(381, 'গোদাগারি', 'Godagari', 24, NULL, NULL, NULL),
	(382, 'মোহনপুর', 'Mohanpur', 24, NULL, NULL, NULL),
	(383, 'পবা', 'Paba', 24, NULL, NULL, NULL),
	(384, 'পুঠিয়া', 'Puthia', 24, NULL, NULL, NULL),
	(385, 'তানোর', 'Tanore', 24, NULL, NULL, NULL),
	(386, 'সিরাজগঞ্জ সদর', 'Sirajganj Sadar Upazila', 25, NULL, NULL, NULL),
	(387, 'বেলকুচি', 'Belkuchi Upazila', 25, NULL, NULL, NULL),
	(388, 'চৌহালি', 'Chauhali Upazila', 25, NULL, NULL, NULL),
	(389, 'কামারখান্দা', 'Kamarkhanda Upazila', 25, NULL, NULL, NULL),
	(390, 'কাজীপুর', 'Kazipur Upazila', 25, NULL, NULL, NULL),
	(391, 'রায়গঞ্জ', 'Raiganj Upazila', 25, NULL, NULL, NULL),
	(392, 'শাহজাদপুর', 'Shahjadpur Upazila', 25, NULL, NULL, NULL),
	(393, 'তারাশ', 'Tarash Upazila', 25, NULL, NULL, NULL),
	(394, 'উল্লাপাড়া', 'Ullahpara Upazila', 25, NULL, NULL, NULL),
	(395, 'বিরামপুর', 'Birampur Upazila', 26, NULL, NULL, NULL),
	(396, 'বীরগঞ্জ', 'Birganj', 26, NULL, NULL, NULL),
	(397, 'বিড়াল', 'Biral Upazila', 26, NULL, NULL, NULL),
	(398, 'বোচাগঞ্জ', 'Bochaganj Upazila', 26, NULL, NULL, NULL),
	(399, 'চিরিরবন্দর', 'Chirirbandar Upazila', 26, NULL, NULL, NULL),
	(400, 'ফুলবাড়ি', 'Phulbari Upazila', 26, NULL, NULL, NULL),
	(401, 'ঘোড়াঘাট', 'Ghoraghat Upazila', 26, NULL, NULL, NULL),
	(402, 'হাকিমপুর', 'Hakimpur Upazila', 26, NULL, NULL, NULL),
	(403, 'কাহারোল', 'Kaharole Upazila', 26, NULL, NULL, NULL),
	(404, 'খানসামা', 'Khansama Upazila', 26, NULL, NULL, NULL),
	(405, 'দিনাজপুর সদর', 'Dinajpur Sadar Upazila', 26, NULL, NULL, NULL),
	(406, 'নবাবগঞ্জ', 'Nawabganj', 26, NULL, NULL, NULL),
	(407, 'পার্বতীপুর', 'Parbatipur Upazila', 26, NULL, NULL, NULL),
	(408, 'ফুলছড়ি', 'Fulchhari', 27, NULL, NULL, NULL),
	(409, 'গাইবান্ধা সদর', 'Gaibandha sadar', 27, NULL, NULL, NULL),
	(410, 'গোবিন্দগঞ্জ', 'Gobindaganj', 27, NULL, NULL, NULL),
	(411, 'পলাশবাড়ী', 'Palashbari', 27, NULL, NULL, NULL),
	(412, 'সাদুল্যাপুর', 'Sadullapur', 27, NULL, NULL, NULL),
	(413, 'সাঘাটা', 'Saghata', 27, NULL, NULL, NULL),
	(414, 'সুন্দরগঞ্জ', 'Sundarganj', 27, NULL, NULL, NULL),
	(415, 'কুড়িগ্রাম সদর', 'Kurigram Sadar', 28, NULL, NULL, NULL),
	(416, 'নাগেশ্বরী', 'Nageshwari', 28, NULL, NULL, NULL),
	(417, 'ভুরুঙ্গামারি', 'Bhurungamari', 28, NULL, NULL, NULL),
	(418, 'ফুলবাড়ি', 'Phulbari', 28, NULL, NULL, NULL),
	(419, 'রাজারহাট', 'Rajarhat', 28, NULL, NULL, NULL),
	(420, 'উলিপুর', 'Ulipur', 28, NULL, NULL, NULL),
	(421, 'চিলমারি', 'Chilmari', 28, NULL, NULL, NULL),
	(422, 'রউমারি', 'Rowmari', 28, NULL, NULL, NULL),
	(423, 'চর রাজিবপুর', 'Char Rajibpur', 28, NULL, NULL, NULL),
	(424, 'লালমনিরহাট সদর', 'Lalmanirhat Sadar', 29, NULL, NULL, NULL),
	(425, 'আদিতমারি', 'Aditmari', 29, NULL, NULL, NULL),
	(426, 'কালীগঞ্জ', 'Kaliganj', 29, NULL, NULL, NULL),
	(427, 'হাতিবান্ধা', 'Hatibandha', 29, NULL, NULL, NULL),
	(428, 'পাটগ্রাম', 'Patgram', 29, NULL, NULL, NULL),
	(429, 'নীলফামারী সদর', 'Nilphamari Sadar', 30, NULL, NULL, NULL),
	(430, 'সৈয়দপুর', 'Saidpur', 30, NULL, NULL, NULL),
	(431, 'জলঢাকা', 'Jaldhaka', 30, NULL, NULL, NULL),
	(432, 'কিশোরগঞ্জ', 'Kishoreganj', 30, NULL, NULL, NULL),
	(433, 'ডোমার', 'Domar', 30, NULL, NULL, NULL),
	(434, 'ডিমলা', 'Dimla', 30, NULL, NULL, NULL),
	(435, 'পঞ্চগড় সদর', 'Panchagarh Sadar', 31, NULL, NULL, NULL),
	(436, 'দেবীগঞ্জ', 'Debiganj', 31, NULL, NULL, NULL),
	(437, 'বোদা', 'Boda', 31, NULL, NULL, NULL),
	(438, 'আটোয়ারি', 'Atwari', 31, NULL, NULL, NULL),
	(439, 'তেতুলিয়া', 'Tetulia', 31, NULL, NULL, NULL),
	(440, 'বদরগঞ্জ', 'Badarganj', 32, NULL, NULL, NULL),
	(441, 'মিঠাপুকুর', 'Mithapukur', 32, NULL, NULL, NULL),
	(442, 'গঙ্গাচরা', 'Gangachara', 32, NULL, NULL, NULL),
	(443, 'কাউনিয়া', 'Kaunia', 32, NULL, NULL, NULL),
	(444, 'রংপুর সদর', 'Rangpur Sadar', 32, NULL, NULL, NULL),
	(445, 'পীরগাছা', 'Pirgachha', 32, NULL, NULL, NULL),
	(446, 'পীরগঞ্জ', 'Pirganj', 32, NULL, NULL, NULL),
	(447, 'তারাগঞ্জ', 'Taraganj', 32, NULL, NULL, NULL),
	(448, 'ঠাকুরগাঁও সদর', 'Thakurgaon Sadar Upazila', 33, NULL, NULL, NULL),
	(449, 'পীরগঞ্জ', 'Pirganj Upazila', 33, NULL, NULL, NULL),
	(450, 'বালিয়াডাঙ্গি', 'Baliadangi Upazila', 33, NULL, NULL, NULL),
	(451, 'হরিপুর', 'Haripur Upazila', 33, NULL, NULL, NULL),
	(452, 'রাণীসংকইল', 'Ranisankail Upazila', 33, NULL, NULL, NULL),
	(453, 'আজমিরিগঞ্জ', 'Ajmiriganj', 51, NULL, NULL, NULL),
	(454, 'বানিয়াচং', 'Baniachang', 51, NULL, NULL, NULL),
	(455, 'বাহুবল', 'Bahubal', 51, NULL, NULL, NULL),
	(456, 'চুনারুঘাট', 'Chunarughat', 51, NULL, NULL, NULL),
	(457, 'হবিগঞ্জ সদর', 'Habiganj Sadar', 51, NULL, NULL, NULL),
	(458, 'লাক্ষাই', 'Lakhai', 51, NULL, NULL, NULL),
	(459, 'মাধবপুর', 'Madhabpur', 51, NULL, NULL, NULL),
	(460, 'নবীগঞ্জ', 'Nabiganj', 51, NULL, NULL, NULL),
	(461, 'শায়েস্তাগঞ্জ', 'Shaistagonj Upazila', 51, NULL, NULL, NULL),
	(462, 'মৌলভীবাজার', 'Moulvibazar Sadar', 52, NULL, NULL, NULL),
	(463, 'বড়লেখা', 'Barlekha', 52, NULL, NULL, NULL),
	(464, 'জুড়ি', 'Juri', 52, NULL, NULL, NULL),
	(465, 'কামালগঞ্জ', 'Kamalganj', 52, NULL, NULL, NULL),
	(466, 'কুলাউরা', 'Kulaura', 52, NULL, NULL, NULL),
	(467, 'রাজনগর', 'Rajnagar', 52, NULL, NULL, NULL),
	(468, 'শ্রীমঙ্গল', 'Sreemangal', 52, NULL, NULL, NULL),
	(469, 'বিসশম্ভারপুর', 'Bishwamvarpur', 53, NULL, NULL, NULL),
	(470, 'ছাতক', 'Chhatak', 53, NULL, NULL, NULL),
	(471, 'দেড়াই', 'Derai', 53, NULL, NULL, NULL),
	(472, 'ধরমপাশা', 'Dharampasha', 53, NULL, NULL, NULL),
	(473, 'দোয়ারাবাজার', 'Dowarabazar', 53, NULL, NULL, NULL),
	(474, 'জগন্নাথপুর', 'Jagannathpur', 53, NULL, NULL, NULL),
	(475, 'জামালগঞ্জ', 'Jamalganj', 53, NULL, NULL, NULL),
	(476, 'সুল্লা', 'Sulla', 53, NULL, NULL, NULL),
	(477, 'সুনামগঞ্জ সদর', 'Sunamganj Sadar', 53, NULL, NULL, NULL),
	(478, 'শান্তিগঞ্জ', 'Shanthiganj', 53, NULL, NULL, NULL),
	(479, 'তাহিরপুর', 'Tahirpur', 53, NULL, NULL, NULL),
	(480, 'সিলেট সদর', 'Sylhet Sadar', 54, NULL, NULL, NULL),
	(481, 'বেয়ানিবাজার', 'Beanibazar', 54, NULL, NULL, NULL),
	(482, 'বিশ্বনাথ', 'Bishwanath', 54, NULL, NULL, NULL),
	(483, 'দক্ষিণ সুরমা', 'Dakshin Surma Upazila', 54, NULL, NULL, NULL),
	(484, 'বালাগঞ্জ', 'Balaganj', 54, NULL, NULL, NULL),
	(485, 'কোম্পানিগঞ্জ', 'Companiganj', 54, NULL, NULL, NULL),
	(486, 'ফেঞ্চুগঞ্জ', 'Fenchuganj', 54, NULL, NULL, NULL),
	(487, 'গোলাপগঞ্জ', 'Golapganj', 54, NULL, NULL, NULL),
	(488, 'গোয়াইনঘাট', 'Gowainghat', 54, NULL, NULL, NULL),
	(489, 'জয়ন্তপুর', 'Jaintiapur', 54, NULL, NULL, NULL),
	(490, 'কানাইঘাট', 'Kanaighat', 54, NULL, NULL, NULL),
	(491, 'জাকিগঞ্জ', 'Zakiganj', 54, NULL, NULL, NULL),
	(492, 'নবীগঞ্জ', 'Nobigonj', 54, NULL, NULL, NULL),
	(493, 'test12', 'test12', 1, NULL, '2017-01-28 05:30:50', '2017-01-28 05:30:50');
/*!40000 ALTER TABLE `thanas` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
